version: '3'
services:
    web:
        image: nginx:alpine
        volumes:
            - ./scripts/nginx/default.conf:/etc/nginx/conf.d/default.conf
            - ./web:/var/www/html
        ports:
            - "80:80"
        restart: always
        depends_on:
            - php
            - mysqldb
    php:
        image: nanoninja/php-fpm:${PHP_VERSION}
        restart: always
        volumes:
            - ./scripts/php/php.ini:/usr/local/etc/php/conf.d/php.ini
            - ./web:/var/www/html

    mysqldb:
        image: mysql:${MYSQL_VERSION}
        container_name: ${MYSQL_HOST}
        restart: always
        env_file:
            - ".env"
        environment:
            - MYSQL_DATABASE=${MYSQL_DATABASE}
            - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
            - MYSQL_USER=${MYSQL_USER}
            - MYSQL_PASSWORD=${MYSQL_PASSWORD}
        ports:
            - "3306:3306"
        volumes:
            - ./database.sql:/docker-entrypoint-initdb.d/init-script.sql
            - ./data_mysql:/var/lib/mysql